stages:
  - build
  - test
  - deploy

build:
  image: java:8
  stage: build
  script:
    - ./gradlew build -x test

    
test:
  stage: test
  image: java:8
  script:
  - ./gradlew test
  
github_deploy:
   stage: deploy
   image: docker:git
   script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$GITHUB_KEY")
   - mkdir -p ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - git remote add github git@github.com:VU-Programming/IJVM-Skeleton.git
   - git push github master
   only:
   - master